name: Merge Release Into Develop

on:
    push:
        branches:
            - 'releases/*'
jobs:
    main:
        name: Create PR Release to Develop
        runs-on: ubuntu-latest
        steps:
            - name: git checkout
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            
            - name: create pull request
              id: open-pr
              uses: repo-sync/pull-request@v2.12.1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                destination_branch: ${{ github.event.repository.default_branch }}
                pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
                pr_body: "Automated Pull Request"
                pr_reviewer: "dcortes22"


