name: tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.2.app && /usr/bin/xcodebuild -version
    - name: Run tests
      run: xcodebuild test -scheme TestProject -project TestProject.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 1214,OS=16.2' | xcpretty && exit ${PIPESTATUS[0]}